---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::coreutils=9.5
  - conda-forge::gzip=1.14
  - conda-forge::tar=1.35
  - conda-forge::curl=8.16.0
